apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapportering-personregister
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  replicas:
<<<<<<< Updated upstream
    min: 6
    max: 10
=======
    min: 2
    max: 4
>>>>>>> Stashed changes
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: {{ kafka.pool }}
  {{#if ingresses}}
  ingresses:
    {{#each ingresses as |url|}}
     - {{url}}
    {{/each}}
  {{/if}}
  leaderElection: true
  observability:
    logging:
      destinations:
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        tier: db-custom-1-3840
        pointInTimeRecovery: true
        databases:
          - name: dp-rapportering-personregister
            envVarPrefix: DB
        flags:
            - name: cloudsql.enable_pgaudit
              value: "on"
            - name: pgaudit.log
              value: 'write'
  accessPolicy:
    inbound:
      rules:
        - application: dp-rapportering
        {{#each additionalInbounds}}
        - application: {{application}}
          namespace: {{namespace}}
        {{/each}}
    outbound:
      external:
        - host: dagpenger-unleash-api.nav.cloud.nais.io
      rules:
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
          cluster: {{ cluster }}
        - application: paw-kafka-key-generator
          namespace: paw
          cluster: {{ cluster }}
  envFrom:
    - secret: dp-rapportering-personregister-unleash-api-token
  env:
    - name: ARBEIDSSOKERREGISTER_OPPSLAG_HOST
      value: {{ ARBEIDSSOKERREGISTER_OPPSLAG_HOST }}
    - name: ARBEIDSSOKERREGISTER_OPPSLAG_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_OPPSLAG_SCOPE }}
    - name: ARBEIDSSOKERREGISTER_RECORD_KEY_HOST
      value: {{ ARBEIDSSOKERREGISTER_RECORD_KEY_HOST }}
    - name: ARBEIDSSOKERREGISTER_RECORD_KEY_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_RECORD_KEY_SCOPE }}
    - name: ARBEIDSSOKERPERIODER_TOPIC
      value: {{ ARBEIDSSOKERPERIODER_TOPIC }}
    - name: BEKREFTELSE_PAA_VEGNE_AV_TOPIC
      value: {{ BEKREFTELSE_PAA_VEGNE_AV_TOPIC }}
    - name: KAFKA_EXTRA_TOPIC
      value: {{ KAFKA_EXTRA_TOPIC }}
