apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapportering-personregister
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  kafka:
    pool: {{ kafka.pool }}
  ingresses:
    - https://dp-rapportering-personregister.intern.dev.nav.no
  observability:
    logging:
      destinations:
        - id: elastic
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        databases:
          - name: dp-rapportering-personregister
            envVarPrefix: DB
        tier: db-custom-1-3840