apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapportering-personregister
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  leaderElection: true
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: {{ kafka.pool }}
  ingresses:
    - https://dp-rapportering-personregister.intern.dev.nav.no
  observability:
    logging:
      destinations:
        - id: elastic
  env:
    - name: ARBEIDSSOKERREGISTER_HOST
      value: {{ ARBEIDSSOKERREGISTER_HOST }}
    - name: ARBEIDSSOKERREGISTER_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_SCOPE }}
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        databases:
          - name: dp-rapportering-personregister
            envVarPrefix: DB
        tier: db-custom-1-3840
  accessPolicy:
    outbound:
      rules:
        - application: paw-arbeidssoekerregisteret-api-oppslag
    inbound:
      rules:
        - application: dp-rapportering
        - application: tokenx-token-generator
          namespace: aura
          cluster: dev-gcp