apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-rapportering-personregister
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: {{ kafka.pool }}
  ingresses:
    - https://dp-rapportering-personregister.intern.dev.nav.no
  leaderElection: true
  observability:
    logging:
      destinations:
        - id: elastic
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        highAvailability: true
        diskAutoresize: true
        databases:
          - name: dp-rapportering-personregister
            envVarPrefix: DB
        tier: db-custom-1-3840
  accessPolicy:
    inbound:
      rules:
        - application: dp-rapportering
        {{#each additionalInbounds}}
        - application: {{application}}
          namespace: {{namespace}}
        {{/each}}
    outbound:
      rules:
        - application: paw-arbeidssoekerregisteret-api-oppslag
          namespace: paw
          cluster: dev-gcp
        - application: paw-kafka-key-generator
          namespace: paw
          cluster: dev-gcp
  env:
    - name: ARBEIDSSOKERREGISTER_OPPSLAG_HOST
      value: {{ ARBEIDSSOKERREGISTER_OPPSLAG_HOST }}
    - name: ARBEIDSSOKERREGISTER_OPPSLAG_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_OPPSLAG_SCOPE }}
    - name: ARBEIDSSOKERREGISTER_RECORD_KEY_HOST
      value: {{ ARBEIDSSOKERREGISTER_RECORD_KEY_HOST }}
    - name: ARBEIDSSOKERREGISTER_RECORD_KEY_SCOPE
      value: {{ ARBEIDSSOKERREGISTER_RECORD_KEY_SCOPE }}
    - name: ARBEIDSSOKERPERIODER_TOPIC
      value: {{ ARBEIDSSOKERPERIODER_TOPIC }}
    - name: BEKREFTELSE_PAA_VEGNE_AV_TOPIC
      value: {{ BEKREFTELSE_PAA_VEGNE_AV_TOPIC }}