apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: test-topic
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: nav-dev
  acl:
    - team: teamdagpenger
      application: dp-rapportering-personregister
      access: readwrite   # read, write, readwrite
    - team: teamdagpenger
      application: abdifatah-bashi
      access: readwrite
    - team: teamdagpenger
      application: yrjanaff
      access: readwrite