apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: dp-rapportering-personregister
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamdagpenger
  secretName: dp-rapportering-personregister-unleash-api-token
  environment: {{ unleashEnv }}
