### Personstatus
GET https://dp-rapportering-personregister.intern.dev.nav.no/personstatus
Accept: application/json
Authorization: Bearer <token>


### Kafka
POST https://dp-rapportering-personregister.intern.dev.nav.no/test
Content-Type: application/json

{
  "periodeId": "7a1b0779-ac3f-439d-a489-be51e91a568e"
}

### Personstatus
GET https://dp-rapportering-personregister.intern.dev.nav.no/isAlive